### ISSUE TITLE
专业点好不啦

### ISSUE THREAD

**Issue by freshopenair** [minxiaoming/NiceAppDemo#1]
我直接开源得了，本来代码我也没混淆。但是你也专业点啊，连我写的类名都没改。

**Comment by minxiaoming** [comment]
你是最美的开发人员嘛？

**Comment by minxiaoming** [comment]
如果是的话，那抱歉了，当初我老板一定要我做出这个效果，我才刚工作，没什么头绪，就反编译了最美应用了，后来我同事问我是怎么实现的，我就想着写一个博客了

**Comment by freshopenair** [comment]
因为这个牵扯到知识产权，你没有得到我们的允许不能这样开源我们的代码。

**Comment by minxiaoming** [comment]
好的，只要你说明你的来历我会将这个项目删除的

**Comment by ihappyhacking** [comment]
@freshopenair 那你开源啊
没改类名那是尊重你们，改了之后你会说什么？是不是就开骂了？
谁让你不混淆的，做开发难道没有这个觉悟吗？自己没有做好安全防范，被人反编译了跑过来说。

**Comment by xu6148152** [comment]
ls是强盗言论。真要脸

**Comment by markzhai** [comment]
路过....lss说的有点过分了...不过po主好歹改下实现嘛 哈哈哈

**Comment by fkysly** [comment]
这什么东西嘛，一个反编译做的DEMO就这么多人star？

ihappyhacking还要点脸？反编译开源别人应用，还怪别人不混淆，没做好安全防范？

**Comment by minxiaoming** [comment]
因为这个问题吵起来了，ihappyhacking 是我朋友，如果觉的他有什么问题可以算在我身上，@freshopenair 你联系下我邮箱minxiaoming07@gmail.com 和我说下你是什么人，我会将这些代码删除的

**Comment by fkysly** [comment]
删什么吗？把证据留下来啊，让大家都来围观看看你朋友是怎么样蔑视知识产权的？反编译别人代码、自己开源，还有理？还把别人说了一顿？人家原作者错在哪儿了？

**Comment by ihappyhacking** [comment]
我蔑视知识产权？是作者说不如自己开源得了，就算他开玩笑，我当真不行吗？反编译别人代码有什么问题吗？反编译别人代码那是因为觉得别人这个效果做的不错，想学习一下，才会去反编译，不然没事闲着蛋疼去反编译？minxiaoming 把这个代码分享出来也是为了帮助有需要的人，作者如果觉得不妥，可以直接发邮件要求删除啊，何必 CSDN 上和 GitHub 上都追着来说差不多的话呢？

**Comment by ihappyhacking** [comment]
还有啊，请问你用过盗版软件吗？你敢说你一直尊重别人的知识产权吗？
反正我有用盗版软件，也有买过软件。

**Comment by fkysly** [comment]
你有逻辑么，人家作者开玩笑说什么，跟你有什么关系。你自己当真还有理了？反编译别人代码当然没有什么问题，但是反编译之后，自己开源放到github上，连类名都懒得改。更关键是还喷人家作者说是因为人家代码没有安全规范、没有代码混淆，所以才连类名都懒得改，这样的逻辑真的太搞笑了吧？

你想学习，你自己反编译，放在你本地怎么玩都没关系，拿到github上来开源，人家原作者过来说你两句，你还有理了？这种代码分享不分享，是人家原作者自己应该干的事情，要你瞎帮忙什么的，真是丢脸都丢到github上来了。

你自己反编译人家代码，放到github上来，还要人家作者怎么怎么样去跟你沟通，你才删掉代码，真是脸皮厚。

**Comment by ihappyhacking** [comment]
首先，我要纠正的是："更关键是还喷人家作者说是因为人家代码没有安全规范、没有代码混淆，所以才连类名都懒得改"，我没有说他代码没有安全规范，我是说他自己也说了的，没有做混淆，这个就是一个安全隐患，容易被人反编译，"所以才连类名都懒得改"，请问，我和 minxiaoming 都没有说过这话，是作者说的，我是说类名懒得改是尊重人家，当然，你也可以说我这么说不对，反编译人家代码然后分享出来这是不尊重人家的，那我也接受。
怎么？你是看不惯别人反编译一个 App 之后拿源码来分享吗？然后被好多人 Star？眼红了？
作者可以直接要求说不能这么分享，直接要求删除，请问作者两次有这么直接明白的说明吗？还有，别人分享是别人的事情，你说"这种代码分享不分享，是人家原作者自己应该干的事情，要你瞎帮忙什么的"，那我说那些话关你屁事？是，我丢脸了，你还真有脸了。
"还要人家作者怎么怎么样去跟你沟通"，发现你真是不仔细看，我一直都是说作者直接要求删除，那么就删除这个 repo，哪里说要怎么怎么样沟通了？
对了，你不是说知识产权吗？怎么不继续说了？我还想知道你都有买过哪些软件，是不是用的所有收费软件你都是自己花钱买的。

**Comment by fkysly** [comment]
现在你们把之前的评论删掉了，就开始赖账了。你开始根本不是说什么类名懒得改是尊重人家，现在说什么，你都能扯开了。有本事找support把评论恢复回来，看看当时你们自己怎么说的？不心虚干嘛删评论呢？自己说的话，现在不敢放出来了？我眼红这个项目被好多人star？这种拿别人代码来做自己项目的，还好意思说这个？

你懂什么叫开源么？人家作者还要直接告诉你不能这么分享？你用了这么久github，连开源的守则都搞不明白？反编译别人代码，拿到github上，开repo作为自己的项目公布，这种行为做得出来还未自己辩解的人，真是第一次见。

丢脸真是丢大了。

**Comment by ihappyhacking** [comment]
“你开始根本不是说什么类名懒得改是尊重人家，现在说什么，你都能扯开了。”，我说你眼睛真的看仔细了吗？？？我第一条回复作者就是有说“类名懒得改是尊重你们”，我还真没本事找什么 support 恢复评论，你这么屌，你找，就算能恢复，你也别傻眼，OK，minxiaoming 邮箱有记录，给你看我第一条回复的截图，请睁大你的眼：
![](http://i1.tietuku.com/abf41cb4fd5b3c00.jpg)
跟你说话真是累，请你有点脑子，不是我删除的，你说：“自己说的话，现在不敢放出来了？”，真是呵呵了，我要是不敢放出来，还在这跟你扯这么多？minxiaoming 是为了不引起骂战才删除的。
是吗，你不眼红？好吧，就当我说错话了，看看下面这张截图：
![](http://i1.tietuku.com/e003318c70ccde63.jpg)
我就不说什么了。
哦，你懂，你真是懂啊，minixiaoming 博客也有说，这是反编译之后的代码，没说是自己写的啊.
“反编译别人代码，拿到github上，开repo作为自己的项目公布，这种行为做得出来还为自己辩解的人，真是第一次见。”请问 minxiaoming 有做辩解吗？现在是我跟你对骂，你能有点逻辑吗？？？
说好的知识产权呢？哑巴了？

**Comment by xu6148152** [comment]
我都没骂人，竟然把我的评论删掉了。。。

**Comment by minxiaoming** [comment]
抱歉，因为我想要结束这个话题想和这位原作者沟通下，确认他的身份，所以把其他的评论都删除了

xu6148152 <notifications@github.com>于2015年7月26日星期日 13:50写道：
